name: CI

on:
  push:

jobs:
  lint:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v2

        - uses: erlef/setup-beam@v1
          with:
            otp-version: 25.x
            elixir-version: 1.x

        - run: mix deps.get
        - run: mix deps.unlock --check-unused
        - run: mix deps.compile
        - run: mix compile --warnings-as-errors
        - run: mix format --check-formatted

  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - versions:
              otp: 22.x
              elixir: 1.12.x
          - versions:
              otp: 26.x
              elixir: 1.x
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.versions.otp }}
          elixir-version: ${{ matrix.versions.elixir }}

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.versions.elixir }}-${{ matrix.versions.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mix test
